# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  [ push,  pull_request ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      # Assuming the .jar file is located in build/libs and named app.jar. Adjust the path and name as necessary.
      - name: Upload .jar file to server
        uses: appleboy/scp-action@master
        with:
          host: 0.petabyte.farm
          username: root
          port: 12122 # Default SSH port, change if different
          source: "build/libs/*.jar" # Adjust the path to where your .jar files are located
          target: "~/test/" # The target directory on your server, adjust as needed

