# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy to production

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

           # Stop currently running Spring Boot application
      - name: Stop Spring Boot application
        uses: appleboy/ssh-action@master
        with:
          host: 0.petabyte.farm
          username: root
          port: 12122
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            pkill -f 'java -jar'

          # Assuming the .jar file is located in build/libs and named app.jar. Adjust the path and name as necessary.
      - name: Move current .jar to archive
        uses: appleboy/ssh-action@master
        with:
          host: 0.petabyte.farm
          username: root
          port: 12122 # Default SSH port, change if different
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            mv ~/test/build/libs/*.jar ~/test_archive/
     
      # Assuming the .jar file is located in build/libs and named app.jar. Adjust the path and name as necessary.
      - name: Upload .jar file to server
        if: "!contains(runner.job, 'plain')"
        uses: appleboy/scp-action@master
        with:
          host: 0.petabyte.farm
          username: root
          port: 12122 # Default SSH port, change if different
          key: ${{ secrets.SSH_PRIVATE }}
          source: "build/libs/*.jar" # Adjust the path to where your .jar files are located
          target: "~/test2/" # The target directory on your server, adjust as needed

                # Upload properties files to server
      - name: Upload properties files to server
        uses: appleboy/scp-action@master
        with:
          host: 0.petabyte.farm
          username: root
          port: 12122 # Default SSH port, change if different
          key: ${{ secrets.SSH_PRIVATE }}
          source: "build/resources/main/*.properties"
          target: "~/test_properties_archive/"
          
      - name: Run jar file on server
        uses: appleboy/ssh-action@master
        with:
          host: 0.petabyte.farm
          username: root
          port: 12122 # Default SSH port, change if different
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            screen -d -m bash -c "java -jar ~/*.jar"
